### ISSUE TITLE
ustni.md pripomba

### ISSUE THREAD

**Issue by MatejFMF** [Trebsch/Analiza-1#1]
V datoteki ustni.md priporočam uporabo * (namenjeno seznamom) namesto - [ ] (namenjeno checkboxom).

Tako zgleda trenutno:
~~~
- [ ] prva snov
- [ ] druga snov
~~~
- [ ] prva snov
- [ ] druga snov

Tako priporočam:
~~~
* prva snov
* druga snov
~~~
* prva snov
* druga snov

**Comment by Trebsch** [comment]
Hvala za komentar, cenjeni znanec.

Sicer sem seznanjen z razliko med bulletpointom in checkboxom. Namen te datoteke je, da označim točno katere dokaze še ne znam v celoti na pamet; posledično je tukaj uporaba checkboxov upravičena.
